version: "3"

services:

  postgres:
    image: ruleoftech/vehicledata-db:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vehicledata
      POSTGRES_DB: vehicledata
      POSTGRES_PASSWORD: vehicledata
      SEED_DATABASE: "true"